[build]
  command = "npm install && sh build.sh"
  publish = "dist"
  functions = "netlify/functions"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# API redirects - both patterns for compatibility
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Direct API function endpoint access
[[redirects]]
  from = "/.netlify/functions/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# Headers for improved security and caching
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"