[build]
  command = "npm run build"
  publish = "dist"

# Redirect all requests to index.html for single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Handle API routes by proxying to the server
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200