[build]
  command = "sh build.sh"
  publish = "dist"  # Vite's default output directory
  functions = "dist/.netlify/functions"  # Compiled functions location

# Single Page Application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Required for Vite/React hydration
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"